apiVersion: v1
kind: Pod
metadata:
  name: gitopsdemo 
  labels:
    env: gitops 
spec:
  containers:
  - image: iam6hills/dockerdemo:tomcatapp-6
    name: app1
    ports:
    - containerPort: 6060
    imagePullPolicy: Always