apiVersion: v1
kind: Pod
metadata:
  name: gitopsdemo 
  labels:
    env: gitops 
spec:
  containers:
  - image: iam11hills/dockerdemo:tomcatapp-11
    name: app1
    ports:
    - containerPort: 110110
    imagePullPolicy: Always