apiVersion: v1
kind: Pod
metadata:
  name: gitopsdemo 
  labels:
    env: gitops 
spec:
  containers:
  - image: iam7hills/dockerdemo:tomcatapp-7
    name: app1
    ports:
    - containerPort: 7070
    imagePullPolicy: Always