apiVersion: v1
kind: Pod
metadata:
  name: gitopsdemo 
  labels:
    env: gitops 
spec:
  containers:
  - image: iam4hills/dockerdemo:tomcatapp-4
    name: app1
    ports:
    - containerPort: 4040
    imagePullPolicy: Always