apiVersion: v1
kind: Pod
metadata:
  name: gitopsdemo 
  labels:
    env: gitops 
spec:
  containers:
  - image: iam9hills/dockerdemo:tomcatapp-9
    name: app1
    ports:
    - containerPort: 9090
    imagePullPolicy: Always