apiVersion: v1
kind: Pod
metadata:
  name: gitopsdemo 
  labels:
    env: gitops 
spec:
  containers:
  - image: iam{tagversion}hills/dockerdemo:tomcatapp-{tagversion}
    name: app1
    ports:
    - containerPort: {tagversion}0{tagversion}0
    imagePullPolicy: Always